# Generated by Django 6.1 on 2026-08-27 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('objetivo', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveSmallIntegerField(default=1)),
                ('resumo', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('ativo', models.BooleanField(default=True)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-versao'],
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem'), ('framework', 'Framework'), ('banco', 'Banco de dados'), ('front', 'Front-end'), ('infra', 'Infraestrutura'), ('outro', 'Outro')], default='outro', max_length=12)),
            ],
            options={
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Passo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('titulo', models.CharField(max_length=150, verbose_name='título')),
                ('o_que_fazer', models.TextField(blank=True)),
                ('como_fazer', models.TextField(blank=True)),
                ('teoria', models.TextField(blank=True, verbose_name='por que é assim')),
                ('criterios_aceite', models.JSONField(blank=True, default=list)),
                ('armadilhas', models.JSONField(blank=True, default=list)),
                ('recursos', models.JSONField(blank=True, default=list)),
                ('estimativa_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('disponivel', 'Disponível'), ('em_andamento', 'Em andamento'), ('em_revisao', 'Em revisão'), ('concluido', 'Concluído')], default='bloqueado', max_length=13)),
                ('notas_do_aluno', models.TextField(blank=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('concluido_manualmente', models.BooleanField(default=False)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='projetos.etapa')),
            ],
            options={
                'ordering': ['etapa__ordem', 'ordem'],
            },
        ),
        migrations.AddField(
            model_name='etapa',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='projetos.plano'),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('objetivo', models.TextField(help_text='Quanto mais concreto, melhor o plano. Diga o que o programa faz e para quem.', verbose_name='o que você quer construir')),
                ('nivel', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=14, verbose_name='nível')),
                ('horas_por_semana', models.PositiveSmallIntegerField(default=5)),
                ('preferencia_didatica', models.CharField(choices=[('socratico', 'Socrático — me faça pensar antes'), ('direto', 'Direto — me diga o que fazer')], default='socratico', max_length=10, verbose_name='como você quer ser ensinado')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('planejado', 'Planejado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('arquivado', 'Arquivado')], default='rascunho', max_length=13)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to=settings.AUTH_USER_MODEL)),
                ('stacks', models.ManyToManyField(blank=True, related_name='projetos', to='projetos.stack')),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='plano',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='projetos.projeto'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.UniqueConstraint(fields=('projeto', 'versao'), name='versao_unica_por_projeto'),
        ),
        migrations.AddConstraint(
            model_name='plano',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('projeto',), name='um_plano_ativo_por_projeto'),
        ),
    ]
