# Generated by Django 6.1 on 2026-08-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='preferencia_didatica',
            field=models.CharField(choices=[('socratico', 'Socrático: me faça pensar antes'), ('direto', 'Direto: me diga o que fazer')], default='socratico', max_length=10, verbose_name='como você quer ser ensinado'),
        ),
    ]
