# Generated by Django 6.1 on 2026-08-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_alter_projeto_preferencia_didatica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passo',
            name='notas_do_aluno',
        ),
    ]
