# Generated by Django 6.1 on 2026-08-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_remove_passo_notas_do_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='passos_prontos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projeto',
            name='briefing_pendente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='erro_geracao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='gerando',
            field=models.BooleanField(default=False),
        ),
    ]
