# Generated by Django 6.1 on 2026-08-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0004_etapa_passos_prontos_projeto_briefing_pendente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='subtitulo',
            field=models.CharField(blank=True, help_text='Escrito pelo mentor ao gerar o plano. Fica em branco até lá.', max_length=200, verbose_name='subtítulo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(blank=True, default='Novo projeto', max_length=120, verbose_name='título'),
        ),
    ]
