# Generated by Django 6.1 on 2026-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0005_projeto_subtitulo_alter_projeto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='passo',
            name='o_que_enviar',
            field=models.CharField(blank=True, max_length=240, verbose_name='o que enviar para revisão'),
        ),
    ]
