# Generated by Django 6.1 on 2026-08-27 23:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversa', to='projetos.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('user', 'Aluno'), ('assistant', 'Mentor')], max_length=10)),
                ('conteudo', models.TextField()),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('versao_prompt', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('tokens_cache_leitura', models.PositiveIntegerField(default=0)),
                ('tokens_cache_escrita', models.PositiveIntegerField(default=0)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('stop_reason', models.CharField(blank=True, max_length=30)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('erro', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='mentoria.conversa')),
                ('passo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos.passo')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
    ]
