# Generated by Django 6.1 on 2026-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='chave_api_cifrada',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='limite_mensal_usd',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usar_chave_propria',
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_visitante',
            field=models.BooleanField(default=False),
        ),
    ]
