# Generated by Django 6.1 on 2026-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_chave_api_cifrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='limite_proprio_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deixe vazio para usar o limite do sistema.', max_digits=8, null=True, verbose_name='limite mensal próprio (US$)'),
        ),
    ]
