# Generated by Django 6.1 on 2026-08-27 23:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linguagem', models.CharField(blank=True, max_length=30)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('passo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissoes', to='projetos.passo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veredito', models.CharField(choices=[('atende', 'Atende'), ('atende_com_ressalvas', 'Atende com ressalvas'), ('nao_atende', 'Ainda não atende')], max_length=20)),
                ('resumo', models.TextField(blank=True)),
                ('criterios_avaliados', models.JSONField(blank=True, default=list)),
                ('pontos_fortes', models.JSONField(blank=True, default=list)),
                ('problemas', models.JSONField(blank=True, default=list)),
                ('proximo_passo_sugerido', models.TextField(blank=True)),
                ('modelo', models.CharField(blank=True, max_length=60)),
                ('custo_usd', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=10)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('submissao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revisao', to='revisoes.submissao')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
