# Generated by Django 6.1 on 2026-08-28 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissao',
            name='linguagem',
        ),
    ]
